This is makeindex, version 2.15 [TeX Live 2014] (kpathsea + Thai support).
Scanning style file /Users/krzysztofwrobel/Documents/MasterThesisPol/.texpadtmp/thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/krzysztofwrobel/Documents/MasterThesisPol/.texpadtmp/thesis.acn...done (0 entries accepted, 0 rejected).
Nothing written in /Users/krzysztofwrobel/Documents/MasterThesisPol/.texpadtmp/thesis.acr.
Transcript written in /Users/krzysztofwrobel/Documents/MasterThesisPol/.texpadtmp/thesis.alg.
